# Generated by Django 4.1.3 on 2023-01-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deguWeb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cog_gene", name="id_cog",),
        migrations.RemoveField(model_name="cog_gene", name="id_gene",),
        migrations.RemoveField(model_name="ec", name="id_EC",),
        migrations.RemoveField(model_name="ec_gene", name="id_ec",),
        migrations.RemoveField(model_name="ec_gene", name="id_gene",),
        migrations.RemoveField(model_name="eggnog_og", name="id_eggnogoggene",),
        migrations.RemoveField(model_name="eggnogoggene_gene", name="id_eggnogoggene",),
        migrations.RemoveField(model_name="eggnogoggene_gene", name="id_gene",),
        migrations.RemoveField(model_name="gene", name="cluster",),
        migrations.RemoveField(model_name="genomeversion", name="id_specie",),
        migrations.RemoveField(model_name="genomeversion_gene", name="id_gene",),
        migrations.RemoveField(
            model_name="genomeversion_gene", name="id_genomeversion",
        ),
        migrations.RemoveField(model_name="genontology", name="id_genontology",),
        migrations.RemoveField(model_name="genontology_gen", name="id_gene",),
        migrations.RemoveField(model_name="genontology_gen", name="id_geneontology",),
        migrations.DeleteModel(name="CLUSTER",),
        migrations.DeleteModel(name="COG",),
        migrations.DeleteModel(name="COG_GENE",),
        migrations.DeleteModel(name="EC",),
        migrations.DeleteModel(name="EC_GENE",),
        migrations.DeleteModel(name="EGGNOG_OG",),
        migrations.DeleteModel(name="EGGNOGOGGENE_GENE",),
        migrations.DeleteModel(name="GENE",),
        migrations.DeleteModel(name="GENOMEVERSION",),
        migrations.DeleteModel(name="GENOMEVERSION_GENE",),
        migrations.DeleteModel(name="GENONTOLOGY",),
        migrations.DeleteModel(name="GENONTOLOGY_GEN",),
    ]
