# Generated by Django 4.1.3 on 2023-01-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deguWeb", "0002_remove_cog_gene_id_cog_remove_cog_gene_id_gene_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="GO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("go", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="specie",
            name="code",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.CreateModel(
            name="EggNOGOG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="default", max_length=50)),
                ("ensembl", models.CharField(max_length=50)),
                (
                    "eggnogogId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deguWeb.eggnogog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterSpecie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clusterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deguWeb.cluster",
                    ),
                ),
                (
                    "specieId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deguWeb.specie"
                    ),
                ),
            ],
        ),
    ]
