# Generated by Django 4.1.3 on 2023-02-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deguWeb", "0005_cazy_keggbrite_keggko_keggmodule_keggpathway_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eggnogog",
            name="cladeId",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="deguWeb.clade",
            ),
        ),
        migrations.AlterField(
            model_name="eggnogog",
            name="parentId",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="deguWeb.eggnogog",
            ),
        ),
    ]
