from django.contrib import admin
from .models import Type, Role, Users, Specie, Cluster, Gene, GenomeVersion, GenomeVersionGene, GO, GOGene, GOParentChild, COG, COGGene, Clade, EggNOGOG, EggNOGOGGene, BiGG, BiGGGene, EC, ECGene, KEGGKO, KEGGKOGene, KEGGModule, KEGGModuleGene, KEGGPathway, KEGGPathwayGene, KEGGReaction, KEGGReactionGene, KEGGrclass, KEGGrclassGene, KEGGBRITE, KEGGBRITEGene, KEGGTC, KEGGTCGene, PFAM, PFAMGene, CAZy, CAZyGene

# Register your models here.
admin.site.register(Type)
admin.site.register(Role)
admin.site.register(Users)

admin.site.register(Specie)
admin.site.register(Cluster)
admin.site.register(Gene)
admin.site.register(GenomeVersion)
admin.site.register(GenomeVersionGene)

admin.site.register(GO)
admin.site.register(GOGene)
admin.site.register(GOParentChild)
admin.site.register(COG)
admin.site.register(COGGene)
admin.site.register(Clade)
admin.site.register(EggNOGOG)
admin.site.register(EggNOGOGGene)
admin.site.register(BiGG)
admin.site.register(BiGGGene)
admin.site.register(EC)
admin.site.register(ECGene)
admin.site.register(KEGGKO)
admin.site.register(KEGGKOGene)
admin.site.register(KEGGModule)
admin.site.register(KEGGModuleGene)
admin.site.register(KEGGPathway)
admin.site.register(KEGGPathwayGene)
admin.site.register(KEGGReaction)
admin.site.register(KEGGReactionGene)
admin.site.register(KEGGrclass)
admin.site.register(KEGGrclassGene)
admin.site.register(KEGGBRITE)
admin.site.register(KEGGBRITEGene)
admin.site.register(KEGGTC)
admin.site.register(KEGGTCGene)
admin.site.register(PFAM)
admin.site.register(PFAMGene)
admin.site.register(CAZy)
admin.site.register(CAZyGene)